TeamOk.WorkFrontend/src/TeamOk.WorkFrontend.Facade/Controllers/KioskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TeamOk.WorkFrontend.Facade.Models;
using TeamOk.WorkFrontend.Facade;
using Microsoft.AspNetCore.Http;
using TeamOk.WorkFrontend.Facade.Generated.Models;

namespace TeamOk.WorkFrontend.Facade.Controllers
{
    public class KioskController : Controller
    {

        private readonly IWerkplekkenBackend _context;

        public KioskController(IWerkplekkenBackend context)
        {
            _context = context;
        }


        public IActionResult Index([FromQuery] string MacAddress)
        {
            if (MacAddress != null && isValideMac(MacAddress))
            {
                HttpContext.Session.SetString("MacAddress", MacAddress);
            }
            if (HttpContext.Session.GetString("MacAddress") != null) {
                MacAddress = HttpContext.Session.GetString("MacAddress");
                if (getIsBezet(MacAddress))
                {
                   //ViewData["localtime"] = HttpContext.Session.GetString("ClaimedUntill") + "now: " + DateTime.Now.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss");
                    ViewData["time"] = HttpContext.Session.GetString("ClaimedUntill");
                    return View("Bezet");
                }
                else
                {
                    return View("Vrij");
                }
            }
            return View("Error");
        }

        public Boolean isValideMac(string mac)
        {
            StatusViewModel Status = null;
            try {
                Status = _context.ApiWorkspaceunitsByMacAddressGet(mac);
            }
            catch (Microsoft.Rest.HttpOperationException exception)
            {
                HttpContext.Session.Clear();
                return false;
                
            }
            if (!(Status == null))
            {
                return true;
            }
            return false;
        }

                 
        private bool getIsBezet(string mac)
        {
            StatusViewModel Status;
            try
            {
                Status = _context.ApiWorkspaceunitsByMacAddressGet(mac);
                bool isClaimed = (bool)Status.Claimed;
                if (isClaimed) { HttpContext.Session.SetString("ClaimedUntill", Status.ClaimedUntill.Value.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss")); }
                return isClaimed;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return false;
            }
        }

   
        public IActionResult geefWerkplekVrij()
        {
            try
            {
                var MacAddress = HttpContext.Session.GetString("MacAddress");
                StatusViewModel modelToPost = new StatusViewModel();
                StatusViewModel postedModel = new StatusViewModel();
                if (getIsBezet(MacAddress))
                {
                    StatusViewModel status = new StatusViewModel();
                    status.ClaimedUntill = DateTime.Now.ToUniversalTime();
                    status.Claimed = false;
                    modelToPost = status;
                    postedModel = _context.ApiWorkspaceunitsByMacAddressPost(MacAddress, status);
                }
                return Index(null);
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        
        public IActionResult reserveerWerkplek()
        {
            var MacAddress = HttpContext.Session.GetString("MacAddress");
            StatusViewModel modelToPost = new StatusViewModel();
            StatusViewModel postedModel =  new StatusViewModel();
            if (!getIsBezet(MacAddress))
            {
                double? Minutes = Convert.ToDouble(Request.Cookies["ChosenMinutes"]);
                double? Hours = Convert.ToDouble(Request.Cookies["ChosenHours"]);
                if (Minutes != 0 || Hours != 0)
                {

                    StatusViewModel status = new StatusViewModel();
                    status.ClaimedUntill = DateTime.Now.ToUniversalTime().AddMinutes((double) Minutes).AddHours((double) Hours);
                    status.Claimed = true;
                    modelToPost = status;
                    postedModel = _context.ApiWorkspaceunitsByMacAddressPost(MacAddress, status);
                }
                else
                {
                    StatusViewModel status = new StatusViewModel();
                    status.ClaimedUntill = DateTime.Now.ToUniversalTime().AddMinutes(30).AddHours(0);
                    status.Claimed = true;
                    modelToPost = status;
                    postedModel = _context.ApiWorkspaceunitsByMacAddressPost(MacAddress, status);
                }
                HttpContext.Session.SetString("ClaimedUntill", modelToPost.ClaimedUntill.Value.ToString("yyyy-MM-dd HH:mm:ss"));
                
            }
            return Index(null);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Voor meer info";
            ViewData["URL"] = "goo.gl/jOHd8R";
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult Timer()
        {
            return View();
        }

        public IActionResult ChooseTime(ChosenTimeModel model)
        {
            var MacAddress = HttpContext.Session.GetString("MacAddress");
            int hours = model.Hours;
            int minutes = model.Minutes;
            CookieOptions options = new CookieOptions();
            Response.Cookies.Append("ChosenHours", hours.ToString(), options);
            Response.Cookies.Append("ChosenMinutes", minutes.ToString(), options);

            return Index(null);
        }

    }
}

TeamOk.WorkFrontend/src/TeamOk.WorkFrontend.Facade/Views/Kiosk/About.cshtml
@ViewData["Message"] - @ViewData["Url"]

<img class="center-block img-responsive scaleable" src="~/images/qr-google-nl.svg"/>

TeamOk.WorkFrontend/src/TeamOk.WorkFrontend.Facade/Views/Kiosk/Bezet.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<script src="~/js/Bezet.js" time=@ViewData["time"]></script>
<div class="claimwerkplekbutton">
@using (Html.BeginForm("geefWerkplekVrij", "Kiosk", FormMethod.Post))
{
    <button value="submit" name="submit" class="btn-block btn-block-styling" style="background-color: red" id="button">Geef werkplek vrij</button>
}
</div>
<meta http-equiv="refresh" content="5; url=./" />
<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />

TeamOk.WorkFrontend/src/TeamOk.WorkFrontend.Facade/Views/Kiosk/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TeamOk.WorkFrontend/src/TeamOk.WorkFrontend.Facade/Views/Kiosk/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    Loading...
</div>

TeamOk.WorkFrontend/src/TeamOk.WorkFrontend.Facade/Views/Kiosk/Timer.cshtml
@model TeamOk.WorkFrontend.Facade.Generated.Models.ChosenTimeModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="~/lib/duration/timingfield.css" rel="stylesheet">
@using (Html.BeginForm("ChooseTime", "Kiosk", FormMethod.Post))
{
<input type="text" class="timing">
<button type="submit" value="Submit" style="width:91vw; position:relative; height: 20vh;"> Klik hier om te kiezen</button>
}
<script src="//code.jquery.com/jquery.min.js"></script>
<script src="~/lib/duration/timingfield.js"></script>
<script>
$(".timing").timingfield({
        maxHour:        23,
        width: "100vw",
    hoursText:      'uur',
    minutesText:    'min',
});
</script>

TeamOk.WorkFrontend/src/TeamOk.WorkFrontend.Facade/Views/Kiosk/Vrij.cshtml
<div class="claimwerkplekbutton" >
    @using (Html.BeginForm("reserveerWerkplek", "Kiosk", FormMethod.Post))
    {
        <button type="submit" value="submit" class="btn-block btn-block-styling" style="background-color: forestgreen">Claim Werkplek</button>
    }
</div>
<meta http-equiv="refresh" content="5; url=./" />

TeamOk.WorkFrontend/src/TeamOk.WorkFrontend.Facade/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)

</head>
<body>
    <div class="navbar navbar-default navbar-static-top navigation-bar">
        <div>
            <div>
                <ul class="nav navigation-items">
                    <li class="list"><a asp-area="" asp-controller="Kiosk" asp-action="About"><img src="~/images/ic_info_black_24px.svg" /></a></li>
                    <li class="list"><a asp-area="" asp-controller="Kiosk" asp-action="Timer"><img src="~/images/ic_watch_later_black_24px.svg" /></a></li>
                    <li class="list"><a asp-area="" asp-controller="Kiosk" asp-action="Index"><img src="~/images/ic_home_black_24px.svg" /></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>